name: Windows tests

on:
  pull_request:
    branches:
      - main

permissions:
   contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  full_build_sdist_wheel:
    # TODO: enable ILP64 once possible
    name: cp311 (build sdist + wheel), full, no pythran
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'environment.yml'

      - name: Win_amd64 - install rtools
        run: |
          # mingw-w64
          choco install rtools -y --no-progress --force --version=4.0.0.20220206
          echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH

      - name: Install OpenBLAS
        shell: bash
        run: |
          # Keep this using the OpenBLAS tarballs for now, as long as we use those for wheel builds
          set -xe
          bash tools/wheels/cibw_before_build_win.sh .
          echo "PKG_CONFIG_PATH=c:\opt\64\lib\pkgconfig;" >> $GITHUB_ENV

      - name: Install meson-python branch
        run: |
          pip install git+https://github.com/thalassemia/meson-python.git@personal

      - name: pip-packages
        run: |
          python -m pip install build delvewheel cython pybind11 meson ninja pytest pytest-xdist pytest-timeout pooch hypothesis
          python -m pip install --pre --upgrade --timeout=60 -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy

      - name: Build
        run: |
          python -m build --no-isolation -x -Csetup-args="-Duse-pythran=false"

          # Vendor openblas.dll and the DLL's it depends on into the wheel 
          $env:wheel_name=Get-ChildItem -Path dist/* -Include *.whl
          delvewheel repair --add-path c:\opt\openblas\openblas_dll -w dist $env:wheel_name
          
          python -m pip install $env:wheel_name

      - name: Test
        run: |
          cd $RUNNER_TEMP
          # run full test suite
          pytest --pyargs scipy

