name: Windows tests

on:
  pull_request:
    branches:
      - main

permissions:
   contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  full_build_sdist_wheel:
    # TODO: enable ILP64 once possible
    name: cp311 (build sdist + wheel), full, no pythran
    runs-on: windows-2019:20231217
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'environment.yml'
      
      - name: Install handle
        run : |
          (New-Object System.Net.WebClient).DownloadFile("https://download.sysinternals.com/files/Handle.zip","Handle.zip");
          Expand-Archive .\Handle.zip .;
          echo "D:\a\scipy\scipy;" >> $env:GITHUB_PATH
          dir .

      - name: Install meson branch
        run: |
          pip install --upgrade psutil
          pip install git+https://github.com/thalassemia/meson.git@personal

      - name: pip-packages
        run: |
          python -m pip install numpy cython build pybind11 meson-python ninja pooch hypothesis

      - name: Build
        run: |
          python -m build --no-isolation -x -Csetup-args="-Duse-pythran=false"

          # Vendor openblas.dll and the DLL's it depends on into the wheel 
          $env:wheel_name=Get-ChildItem -Path dist/* -Include *.whl
          delvewheel repair --add-path c:\opt\openblas\openblas_dll -w dist $env:wheel_name
          
          python -m pip install $env:wheel_name

      - name: Test
        run: |
          cd $RUNNER_TEMP
          # run full test suite
          pytest --pyargs scipy

